serokell/gemini-infra

lib/common/edna/backend-config.nix

Problem: after recent changes edna-server's config file
has a mandatory key `logging`.
Solution: update `backend-config.nix` file to contain this
key. We set it to `Dev` for now.

Add logging field to backend-config of Edna

---

common.nix
lib/common/edna/server.nix
servers/alhena/default.nix
servers/alzirr/default.nix
servers/castor/default.nix
servers/jishui/default.nix
servers/mekbuda/default.nix
terraform/alhena.tf
terraform/castor.tf
terraform/jishui.tf
terraform/main.tf
terraform/mekbuda.tf

Adds wireguard interface which connects each node to polis, and runs prometheus node exporter on that interface.
As I understand, mtg on mekbuda is not working yet (@balsoft correct me if I'm wrong), but we can still enable wireguard there, we just won't add it to prometheus until it's finished.

[OPS-1138] Enable monitoring via wireguard for all nodes

---

flake.lock
lib/common/edna/server.nix

Requires https://github.com/serokell/nixpkgs/pull/49. CI will fail until merged and repinned.
Fetch secret environment variables from Vault for backend container.

[EDNA-117] Fetch secrets for backend container from Vault

---

flake.lock
flake.nix
servers/wasat/default.nix
servers/wasat/wg-keys.nix
terraform/main.tf
terraform/provider.tf
terraform/wasat.tf

Moves wireguard VPN configuration from pluto. Pluto also had nginx server, but I think nobody is using it, so I dropped it. The server is hosted in hetzner cloud because traffic is cheaper than in AWS there.

[OPS-1116] Add wasat instance for VPN

---

flake.lock
servers/alzirr/deployment.nix

This also includes utilizing `addSecurityHeaders = false;` on Alzirr as introduced in https://github.com/serokell/serokell.nix/pull/46 to fix evaluation with a newer serokell.nix version.

Update serokell.nix and add diogo to users on alzirr

---

.gitignore
flake.lock
lib/common/edna/server.nix
servers/alzirr/deployment.nix
servers/castor/default.nix
servers/jishui/default.nix
terraform/main.tf
terraform/provider.tf

Update nix dependencies.
Related issue: https://issues.serokell.io/issue/OPS-1269

[OPS-1269] Bump dependencies

---

.buildkite/pipeline.yml
.gitignore
flake.nix
terraform/main.tf

This is a bit ugly but the best solution I can think of right now, this pins our VPC module using Nix so we are able to use the Nix flake check for Terraform, and removes the need to manually downgrade the VPC module version when initializing terraform.

Pin Terraform VPC module using Nix

---

flake.nix
servers/mebsuta/default.nix
terraform/mebsuta.tf

This should help avoid the possibility of our Wireguard traffic being filtered out

Add iodined tunnel

---

.buildkite/pipeline.yml
flake.nix

Switch from just running `nix flake check` to using `mkPipeline`, and mimic some arbitrary changes made to this config when copying most of it to tezos-infra (where `mkPipeline` is now also used)

Switch to mkPipeline

---

flake.lock
flake.nix

- bumped Nix version to 2.10 in the shell, because 2.7 is incompatible
with some newer URLs in the build
- re-pinned ligo-webide to the main repo
- pre-deployed

[LIGO-485] Updating ligo-webide

---

flake.lock

Problem: @PhilTaken recently joined us as an SRE. We need to grant them access to all existing infra.
Solution: Bump serokell.nix to add Philipp to the list of users with wheel access.

Bump 'serokell.nix'

---

README.md
flake.lock
servers/tejat-prior/default.nix

Problem: Currently deployed webide version is outdated.
Solution: Update flake to use the newest version.
Currently based on https://gitlab.com/serokell/ligo/ligo/-/merge_requests/438

[LIGO-764] update webide and rework it to profile-based approach

---

servers/tejat-prior/default.nix

Problem: Webide team members cannot deploy new webide versions from their machines, also they cannot observe logs and other info since they lack access to the server.
Solution: Grant Sasha and Preetham root access to the tejat-prior server.

Grant webide team access to the tejat-prior

---

servers/tejat-prior/default.nix

Problem: Services inside webide container can silently fail.
Solution: Enable and expose webide container prometheus node exporter. These metrics are exposed on '10100' port and can be added to the prometheus configuration similarly to the host node exporter metrics.

[LIGO-960] Enable and expose webide container node exporter

---

flake.lock
servers/tejat-prior/default.nix

Problem: Webide now needs a token for gist management. We need to securely
provide a such token for our webide deployment.
Solution: Provide gist as a vault secret.
Currently based on https://gitlab.com/serokell/ligo/ligo/-/merge_requests/544.

[LIGO-946] Provide gist management token for our webide deployment

---

flake.lock
flake.nix
modules/cors-proxy.nix
modules/default.nix
servers/tejat-prior/default.nix
terraform/tejat-prior.tf

Problem: Webide needs [cors-proxy](https://github.com/isomorphic-git/cors-proxy) to successfully handle interaction with git repositories.
Solution:
1) Provide cors-proxy instance on tejat-prior.
2) Add ligo-webide-cors-proxy.serokell.team CNAME
that points to tejat-prior.
3) Update nginx to proxy requests on
https://ligo-webide-cors-proxy.serokell.team to cors-proxy.

[LIGO-977] Add cors-proxy instance for webide

---

servers/tejat-prior/default.nix

Problem: Currently webide activation restarts the entire container and
as a result, it's non-trivial to catch services failures that may occur
after container restart. Webide activation profile now runs commands
inside this container. However, 'deploy' user doesn't have sufficient
priviliges to run such commands.
Solution: Add sudoers entry to allow 'deploy' user run commands inside
the webide container via 'nixos-container run ligo-webide-thing'.
Currently based on #66

[LIGO-976] Allow 'deploy' user run commands inside webide container 

---

servers/alzirr/deployment.nix

Problem: oauth2 proxy redirects to 'tt.serokell.io', while this URL is no longer used and its certificate expired. As a result, users see an error in their browsers.
Solution: Add 'tt.serokell.io' to serverAliases of the nginx swampwalk virtual host.

Add 'tt.serokell.io' to serverAliases

---

servers/wasat/wg-keys.nix

Problem: wg-keys.nix configures VPN clients for people who no longer work with us.
Solution: Remove such people from the VPN config.

Cleanup wg-keys.nix

---

servers/wasat/wg-keys.nix

Problem: Rinat no longer works with us :(
Solution: Remove his key from wireguard configuration.

Remove Rinat's key from wireguard configuration

---

flake.lock
flake.nix
servers/tejat-prior/default.nix

Problem: https://github.com/serokell/tzbot is ready to be deployed and tested in our slack workspace.
Solution: Add its service to tejat-prior server.
Currently based on https://github.com/serokell/tzbot/pull/60

[OPS-1409] Add tzbot service to tejat-prior

---

README.md

Problem: Tejat-prior no longer runs webide, but runs tzbot instance.
Solution: Update README table.

[Chore] Update tejat-prior function in README table

---

terraform/alhena.tf
terraform/castor.tf
terraform/jishui.tf
terraform/mekbuda.tf
terraform/tejat-prior.tf

Problem: We need to analyze AWS expenses for instances in this repo. Unfortunately, the only viable way to filter expenses reports is to add name tags to instances.
Solution: Add name tags to AWS instances.

[OPS-1422] Add name tags for AWS instances

---

flake.lock
terraform/alhena.nix
terraform/alzirr.nix
terraform/castor.nix
terraform/jishui.nix
terraform/mebsuta.nix
terraform/tejat-prior.nix
terraform/wasat.nix

Problem: We have added the mkAddressRecords function to terranix-simple, so now we can reduce amount of boilerplate when defining DNS records for ipv4 and ipv6.
Solution: Use mkAddressRecords to refactor DNS records.

[Chore] Refactor DNS records

---

terraform/alhena.nix
terraform/castor.nix
terraform/common.nix
terraform/jishui.nix
terraform/mebsuta.nix
terraform/tejat-prior.nix
terraform/wasat.nix

Problem: We have added the mkAWS and mkHcloud to terranix-simple, so now we can reduce amount of boilerplate when defining aws instances and hcloud servers.
Solution: Use mkAWS and mkHcloud to refactor aws instances and hcloud servers.

[Chore] Refactor aws instances and hcloud servers

---

servers/mebsuta/default.nix
servers/mebsuta/xray.nix

Problem: Wireguard and OpenVPN protocols are blocked by ISPs in _some countries_.
Solution: Add xray server with xtls-based proxy.
For reference: https://xtls.github.io/en/

Add xray server with xtls-based proxy

---

terraform/main.nix

Problem: DNS64 needs a dedicated route for domains that don't have IPv6 record. This route is not provided by the VPC module, thus resolving doesn't work.
Solution: Disable DNS64.

Disable DNS64

---

modules/cors-proxy.nix

Problem: By default, systemd services generated from the NixOS system configuration don't attempt to restart on failure since Restart=no. However, in some cases, running processes can fail for unclear reasons, and the simplest way to bring the failed service back to life is to restart it. Instead, currently, the service will fail and trigger an alert without attempting to restart.
Solution: Add default values for startLimitBurst, startLimitIntervalSec, Restart, and RestartSec.

[OPS-1402] Add systemd unit restart policy

---

common.nix
servers/alzirr/deployment.nix

Problem: We want to harden the security of our systemd services.
Solution: Update hardened services, harden swampwalk service, import serokell-nix.lib.systemd.hardenServices.

[OPS-1161] Harden systemd services

---

common.nix
flake.lock
flake.nix
servers/alzirr/deployment.nix
terraform/alzirr.nix

Update inputs and adjust the configuration

Nixpkgs repin
