README.md, common.nix, flake.lock, flake.nix
Finally use https://github.com/serokell/vault-secrets !
=> Use new vault-secrets and improve documentation

flake.nix, lib/common/edna/backend-config.nix, lib/common/edna/server.nix, servers/jishui/default.nix, servers/jishui/edna.nix, terraform/jishui.tf
Jishui will host the Demo deployment of EDNA.
Related App PR: https://github.com/serokell/edna/pull/33
=> [EDNA-45] Add server Jishui

README.md, flake.lock, servers/alzirr/default.nix, servers/alzirr/deployment.nix, servers/alzirr/overlays.nix, servers/alzirr/platform.nix, terraform/alzirr.tf, terraform/main.tf
Pretty much just copied everything from [profiles](https://github.com/serokell/serokell-profiles/pull/545), removing a few things I think are handled by our common config.
=> [OPS-1157] Add server Alzirr to host Swampwalk

flake.lock, servers/alzirr/deployment.nix, terraform/alzirr.tf
Deploy a second copy of Swampwalk
=> [INT-199] Deploy Swampwalk2

servers/wasat/wg-keys.nix
=> Add worm2fed's phone key

servers/wasat/wg-keys.nix
After reboot WireGuard dropped my config.. so now I lost vpn
=> Update worm2fed's travos key

servers/wasat/wg-keys.nix
After iOS update on my phone I lost my wg configuration there. So I created a new key using our instructions. This commit comments out the old key (which is lost) and adds the new one (freshly generated).
=> Update gromakovsky's keys

flake.lock, flake.nix, modules/default.nix, modules/suitecrm.nix, packages/default.nix, packages/suitecrm/default.nix, servers/mekbuda/default.nix, servers/pollux/default.nix, terraform/pollux.tf
Continuation of https://github.com/serokell/gemini-infra/pull/25 which I broke
=> [OPS-1277] Add SuiteCRM

flake.nix, servers/tejat-prior/default.nix, terraform/main.tf, terraform/tejat-prior.tf
Signed-off-by: Magic_RB <magic_rb@redalder.org>
=> [OPS-1278] - Setup Murmur, for Mumble on Tejat-Prior

servers/wasat/wg-keys.nix
I've got a new laptop and want to use our VPN on it
=> Add new rvem laptop to VPN

servers/wasat/wg-keys.nix
It's about time I have a key here I think
=> Add laptop to VPN

servers/wasat/wg-keys.nix
We want it to be accessible within our VPN.
=> Add HQ mac to the VPN

flake.nix
The last patch for this issue had checks erroneously succeeding due to no files being present, and the command wrapper wouldn't work in practice due to $PWD often being the `terraform/` subdirectory, this PR should fix that
=> Fix issues with VPC pinning

flake.lock, flake.nix, servers/tejat-prior/default.nix, terraform/tejat-prior.tf
ligo team needed a service to showcase their stuff
since it invokes compiler with user data, and I am far from being completely sure that it's secure, i wrapped it in a vm
=> ligo-webide: added showcase service

servers/alzirr/deployment.nix
Problem: It's broken and is no longer maintained.
Solution: Remove old swampwalk profile, service and corresponding
nginx configuration.
Currently based on #59
=> Remove old swampwalk deployment

flake.lock
Problem: Webide service configuration was updated.
Solution: Update the corresponding flake input to propagate changes to tejat-prior configuration.
=> Bump webide

flake.lock, servers/tejat-prior/default.nix
Problem: We need to set up CD for https://github.com/serokell/tzbot.
Solution: Add SSH pubkey, adjust tzbot service.
Related to https://github.com/serokell/tzbot/pull/84
=> [OPS-1409] Prepare tzbot service for CD

servers/tejat-prior/default.nix
Problem: Our webide deployment is no longer needed.
Solution: Decommission it from tejat-prior server.
Currently based on #76 to avoid rebase conflicts in the nearby future.
=> Decommission webide deployment

.github/workflows/check.yml, flake.nix
Problem: the current ci/cd is buildkite based, however we are planning to switch to github actions for ci
Solution: switch ci configuration to github actions yml
=> replace buildkite ci

servers/wasat/wg-keys.nix
Problem: Pasquale no longer works with us.
Solution: Remove his key from the VPN setup.
=> [Chore] Remove Pasquale's wg key

flake.lock, flake.nix, lib/common/edna/server.nix, servers/alzirr/platform.nix, servers/wasat/default.nix
Problem: we need to update flake inputs from time to time
Solution:
- update nixpkgs, serokell-nix (and the rest)
- fix terraform license change
- fix infinite recursion related to mdadm.conf
=> [OPS-1514] Repin nixpkgs

servers/alzirr/deployment.nix
=> [Chore] Grant 'lierdakil' access to alzirr

flake.lock, flake.nix
Problem: Currently used xray version from our nixpkgs fork is somewhat old.
Solution: Bump it.
=> [Chore] Bump xray
